#!/bin/bash
catpipe() {
  if (( $1 )); then
    cat | catpipe $(($1 - 1))
  else
    pv
  fi
}

for i in `seq 1200`; do
  echo -en "\r$i/1200" 1>&2
  cat /usr/share/dict/words
done > testdata
clear

for n in 0 0 0 0 0 0 0 0 1 2 4 8 16 32 64 128 256 512 1024; do
  echo "pipeline of size $n"
  catpipe $n < testdata > /dev/null
done

rm testdata
