sudo: required
services:
- docker
before_install:
- docker pull spencertipping/ni-env-dev-arch
- docker pull spencertipping/ni-env-dev-alpine
- docker pull spencertipping/ni-env-dev-ubuntu-14.04
- docker pull spencertipping/ni-env-dev-ubuntu-16.04
- docker pull spencertipping/ni-env-dev-ubuntu-18.04
- docker pull spencertipping/ni-env-dev-ubuntu-20.04
- docker pull spencertipping/ni-env-dev-ubuntu-22.04
- docker pull spencertipping/ni-env-dev-ubuntu-24.04
script:
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-arch ./test --travis
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-alpine ./test --travis
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-ubuntu-14.04 ./test --travis
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-ubuntu-16.04 ./test --travis
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-ubuntu-18.04 ./test --travis
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-ubuntu-20.04 ./test --travis
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-ubuntu-22.04 ./test --travis
- docker run --rm -it -v $PWD:/data -v /var/run/docker.sock:/var/run/docker.sock spencertipping/ni-env-dev-ubuntu-24.04 ./test --travis
