#!/bin/bash
# Builds the ni image, first by assembling the self-modifying parts (./boot),
# and then by telling it to add modules. core/ is symlinked to gen/, which is
# produced by ./boot.

./boot
./ni --internal/lib core/gen
./ni --internal/lib core/meta
./ni --internal/lib core/stream

./ni --internal/lib core/pl

if [[ `./ni //ni/self` != "$(< ni)" ]]; then
  echo "ni is unstable under replication" >&2
  exit 1
fi

wc -c ni
