#!/bin/bash
# Builds the core ni image from the files in src/.
cd $(dirname $0)

cat src/boot \
    src/lib/behavior \
    src/lib/class \
    src/lib/fn \
    src/lib/image \
  > ni0

echo "initially $(wc -c < ni0) bytes"

perl ni0 //ni > ni && cp ni ni0 || exit $?
perl ni0 //ni > ni || exit $?

if [[ "$(<ni0)" != "$(<ni)" ]]; then
  echo 'ni is unstable under replication'
  [[ -n "$(<ni0)" ]] && [[ -n "$(<ni)" ]] && diff -C 3 ni0 ni
  exit 1
else
  rm ni0
fi

chmod 755 ni

if (( ! $# )); then
  seq 10 | xargs -n1 -I{} echo > /dev/null

  ni_startups=20
  start_nanos=$(date +%s%N)
  seq $ni_startups | xargs -n1 -I{} ./ni //ni > /dev/null
  end_nanos=$(date +%s%N)

  echo "$(wc -c < ni) bytes after rewriting" >&2
  echo "$(( (end_nanos - start_nanos) / (ni_startups * 1000) ))μs overhead" >&2
fi
