#!/bin/bash
for file in $(find doc -name '*.md' -type f); do
  dir=$(dirname $file)
  mkdir -p test/${dir#doc}
  perl -ne '$p &= !/^\`\`\`$/; print if $p; $p |= /^\`\`\`sh$/' $file \
    > test/${file#doc/}.transcript
done
