#!/bin/sh
# NB: all of this will be replaced by stuff from src/. This is just a minimal
# first implementation to emit a self-modifying script based on the contents of
# src/.

module() {
  [ $# -eq 2 ] && module_v="$2" || module_v="`cat`"
  eval "module_$module_index=\"\$module_v\""
  [ ${1%.sh} = $1 ] || eval "eval \"\$module_v\"" || echo "in module $1" >&2
  modules="$modules$newline$1"
  module_index=$((module_index + 1))
}

. src/ni/self/fs.sh
inhume src/

main_setup
self > ni0 && chmod +x ni0

eval "$shutdown_hooks"

# Build the actual ni image through two iterations of replication
rm -f ni1 ni
./ni0    --install ni1 && rm ni0 \
  && ni1 --install ni  && rm ni1
