#!/bin/bash
cd $(dirname $0)

envs=( alpine
       centos-5
       centos-6
       debian-wheezy
       ubuntu-12.04
       ubuntu-14.04
       ubuntu-16.04 )

./build
./lazytest $(find doc -name '*.md') > dev/tests.sh

tests() { echo 'cd /tmp; bash /data/dev/tests.sh'; }
image() { docker build -q -f env/$1 .; }

default_image=ubuntu-16.04

docker_magic="--security-opt=seccomp=unconfined"
docker_opts="$docker_magic -i -m 256M --rm -v $PWD:/data:ro"

c=$1
shift
case $c in
-b|--build)
  for e in ${envs[@]}; do
    echo
    echo "BUILDING $e"
    echo
    docker build -f env/$e .
  done
  ;;

-q|--quick)
  tests | docker run $docker_opts $(image ${1:-$default_image}) /bin/bash
  ;;

-r|--repl)
  docker run $docker_opts -t $(image ${1:-$default_image}) /bin/bash
  ;;

*)
  for e in ${envs[@]}; do
    echo
    echo "TESTING $e"
    echo
    tests | docker run $docker_opts $(image $e) /bin/bash
    echo
  done
esac
