#!/bin/bash
cd $(dirname $0)

envs=( alpine
       centos-5
       centos-6
       debian-wheezy
       ubuntu-12.04
       ubuntu-14.04
       ubuntu-16.04
       ubuntu-16.04-p3
       ubuntu-16.10 )

markdowns=( $(ls doc | sed 's/.md$//' ) )

generate_gitlab_ci() {
  for e in ${envs[@]}; do
    echo "$e:"
    echo "  image: spencertipping/ni-env-$e"
    echo "  script:"
    echo "    - ./test --ci"
  done
}

generate_gitlab_ci > .gitlab-ci.yml

if [[ $1 == '-o' ]] || [[ $1 == '--only' ]]; then
  test_set=$2
  shift 2
fi

build_ni_stuff() {
  ./build
  {
    echo cd /tmp
    echo export NI_NO_MONITOR=yes
    ./lazytest ${test_set:-$(find doc bugs -name '*.md')}
  } > dev/tests.sh
}

tests() { rm -f .test-cancel; echo 'bash /data/dev/tests.sh'; }
image() { docker build -q -f env/$1 -t ni/env-$1 .; }

default_image=ubuntu-16.04

docker_dind="-v /var/run/docker.sock:/var/run/docker.sock --privileged"
docker_magic="--security-opt=seccomp=unconfined"
docker_opts="$docker_magic $docker_dind -i -m 256M --rm -v $PWD:/data:ro"

c=$1
shift
case $c in
-b|--build)
  for e in ${envs[@]}; do
    echo
    echo "BUILDING $e"
    echo
    docker build -f env/$e -t ni/env-$e .
  done
  ;;

-q|--quick)
  echo "NOTE: standard error is redirected into test.log"
  build_ni_stuff
  tests | docker run $docker_opts --name ni-test $(image ${1:-$default_image}) /bin/bash 2>test.log
  ;;

-r|--repl)
  echo "NOTE: to run tests, cd /tmp && bash /data/dev/tests.sh"
  build_ni_stuff
  docker run $docker_opts -t --name ni-test-repl $(image ${1:-$default_image}) /bin/bash
  ;;

-c|--cancel)
  touch .test-cancel
  docker rm -f ni-test ni-test-hadoop
  ;;

--ci)
  {
    echo cd /tmp
    echo export NI_NO_MONITOR=yes
    echo export SKIP_DOCKER=yes         # FIXME if possible
    ./lazytest ${test_set:-$(find doc bugs -name '*.md')}
  } > dev/tests.sh
  cp ni /usr/bin/
  bash dev/tests.sh
  ;;

--nop)
  ;;

*)
  echo "NOTE: standard error is redirected into test.log"
  build_ni_stuff
  for e in ${envs[@]}; do
    if [[ -e .test-cancel ]]; then
      rm .test-cancel
      exit 1
    fi
    echo
    echo "TESTING $e"
    echo
    tests | docker run $docker_opts --name ni-test $(image $e) /bin/bash
    echo
  done 2>test.log
esac
