#!/bin/bash
cd $(dirname $0)

envs=( env/alpine env/centos-5 env/ubuntu-16.04 )

./build
./lazytest $(find doc -name '*.md') > tests.sh

if [[ $1 == '-q' ]]; then
  docker run --security-opt=seccomp=unconfined -i -m 256M --rm -v $PWD:/data:ro \
    $(docker build -q -f env/ubuntu-16.04 .) /bin/bash <<'EOF'
    cd /tmp
    bash /data/tests.sh
EOF
elif [[ $1 == '--build' ]]; then
  for e in ${envs[@]}; do
    echo
    echo "BUILDING $e"
    echo
    docker build -f $e .
  done
elif [[ $1 == '--repl' ]]; then
  docker run -it -m 256M --rm -v $PWD:/data $(docker build -q -f env/$2* .) \
    /bin/bash
else
  for e in ${envs[@]}; do
    echo
    echo "TESTING $e"
    echo

    docker run --security-opt=seccomp=unconfined -i -m 256M --rm -v $PWD:/data:ro \
      $(docker build -q -f $e .) /bin/bash <<'EOF'
      cd /tmp
      bash /data/tests.sh
EOF

    echo
  done
fi
