#!/bin/bash
date > /dev/null
ni < /dev/null > /dev/null

ta=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | ni l'a' > /dev/null

tb=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | ni l'(r a)' > /dev/null

tc=$(date +%s%N)

echo -e "ni_lisp_a_256M\t$(((tb - ta) / 1000000))\tms"
echo -e "ni_lisp_ra_256M\t$(((tc - tb) / 1000000))\tms"
