#!/bin/bash
date > /dev/null
ni < /dev/null > /dev/null
nfu < /dev/null > /dev/null

ta=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | ni p'$_' > /dev/null

tb=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | NFU_ALWAYS_VERBOSE= nfu -m '$_' > /dev/null

tc=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | perl -ne 'print' > /dev/null

td=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | ni p'a' > /dev/null

te=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | ni p'r a' > /dev/null

tf=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | ni p'b' > /dev/null

tg=$(date +%s%N)
perl -e '
  my $data = `ni //ni`;
  $data .= $data until length $data >= 1048576;
  $data = substr $data, 0, 1048576;
  syswrite STDOUT, $data for 1..256' \
| pv | ni p'r b' > /dev/null

th=$(date +%s%N)

echo -e "ni_perl_256M\t$(((tb - ta) / 1000000))\tms"
echo -e "nfu_perl_256M\t$(((tc - tb) / 1000000))\tms"
echo -e "perl_256M\t$(((td - tc) / 1000000))\tms"
echo -e "ni_perl_a_256M\t$(((te - td) / 1000000))\tms"
echo -e "ni_perl_ra_256M\t$(((tf - te) / 1000000))\tms"
echo -e "ni_perl_b_256M\t$(((tg - tf) / 1000000))\tms"
echo -e "ni_perl_rb_256M\t$(((th - tg) / 1000000))\tms"
