#!/bin/bash
date > /dev/null
ni < /dev/null > /dev/null
./nfu < /dev/null > /dev/null

datasource() {
  perl -e '
    my $data = `ni //ni`;
    $data .= $data until length $data >= 1048576;
    $data = substr $data, 0, 1048576;
    syswrite STDOUT, $data for 1..256' \
  | pv
}

datasource | NFU_ALWAYS_VERBOSE= nfu -m '$_' > /dev/null

ta=$(date +%s%N); datasource | ni p'$_'  > /dev/null
tb=$(date +%s%N); datasource | ni p'a'   > /dev/null
tc=$(date +%s%N); datasource | ni p'r a' > /dev/null
td=$(date +%s%N); datasource | ni m'a'   > /dev/null
te=$(date +%s%N); datasource | ni m'r a' > /dev/null
tf=$(date +%s%N)

echo -e "ni_perl_256M\t$(((tb - ta) / 1000000))\tms"
echo -e "ni_perl_a_256M\t$(((tc - tb) / 1000000))\tms"
echo -e "ni_perl_ra_256M\t$(((td - tc) / 1000000))\tms"
echo -e "ni_ruby_a_256M\t$(((te - td) / 1000000))\tms"
echo -e "ni_ruby_ra_256M\t$(((tf - te) / 1000000))\tms"
