#!/bin/bash

gb() {
  perl -e '$d = `ni //ni`; syswrite STDOUT, $d while 1' \
    | head -c $((1048576 * 1024))
}

gb | pv > /dev/null
echo | sort > /dev/null

ta=$(date +%s%N)
gb | pv | sort > /dev/null

tb=$(date +%s%N)
gb | pv | sort --buffer-size=64M > /dev/null

tc=$(date +%s%N)
gb | pv | sort --buffer-size=512M > /dev/null

td=$(date +%s%N)
gb | pv | sort --buffer-size=64M --compress-program=gzip > /dev/null

te=$(date +%s%N)
gb | pv | sort --buffer-size=64M --parallel=4 > /dev/null

tf=$(date +%s%N)
gb | pv | sort --buffer-size=64M --parallel=4 --compress-program=gzip > /dev/null

tg=$(date +%s%N)

echo -e "sort_1G\t$(((tb - ta) / 1000000))\tms"
echo -e "sort_S64M_1G\t$(((tc - tb) / 1000000))\tms"
echo -e "sort_S512M_1G\t$(((td - tc) / 1000000))\tms"
echo -e "sort_S64M_gzip_1G\t$(((te - td) / 1000000))\tms"
echo -e "sort_S64M_P4_1G\t$(((tf - te) / 1000000))\tms"
echo -e "sort_S64M_P4_gzip_1G\t$(((tg - tf) / 1000000))\tms"
