#!/bin/bash
ni < /dev/null > /dev/null
./nfu < /dev/null > /dev/null
date > /dev/null

ta=$(date +%s%N)
for i in `seq 100`; do
  ni < /dev/null > /dev/null
done

tb=$(date +%s%N)
for i in `seq 100`; do
  ./nfu < /dev/null > /dev/null
done

tc=$(date +%s%N)

echo -e "ni_startup\t$(( (tb - ta) / 1000000 / 100 ))\tms"
echo -e "nfu_startup\t$(( (tc - tb) / 1000000 / 100 ))\tms"
