#!/bin/sh

self_index=0
self_prefix=${TMPDIR:-/tmp}/ni-$$

until mkdir "$self_prefix-$self_index" 2>/dev/null; do
  self_index=$((self_index + 1))
done

self_dir="$self_prefix-$self_index"

rm_self_dir() rm -r "$self_dir"

trap rm_self_dir EXIT

inline_index=0

inline_file() {
  inline_index=$((inline_index + 1))
  cat <&3 > "$self_dir/$inline_index-$2"
  eval "$1=\"$self_dir/$inline_index-$2\""
}

inline_c() {
  inline_file c_filename x.c
  c99 "$c_filename" -o "${c_filename%.c}"
  "${c_filename%.c}" "$@"
  rm "${c_filename%.c}" "$c_filename"
}

inline_c 3<<EOF
#include <stdio.h>
#include <sys/types.h>
int main() {
  char buf[8192];
  ssize_t n = sizeof(buf);
  while ((n = getline(&buf, &n, stdin)) > 0)
    printf("c program: got %d chars: %s\n", n, buf);
  return 0;
}
EOF
