#!/usr/bin/env perl
use Benchmark qw/:all/;
use Time::HiRes qw/time/;

my $perl_ns   = join ',', 1..1000;
(my $packed_ns = pack 'N/N', 1..1000) =~ s/#/\\#/g;
my $perl_packed_ns = "unpack 'N/N', q#$packed_ns#";

cmpthese 10000, {
  parse => sub {@xs = eval $perl_ns},
  unpack => sub {@xs = eval $perl_packed_ns}
};
