#!/usr/bin/env perl
use Benchmark qw/:all/;

# The goal is to construct this object:
#
# [
#   {
#     foo => [1, 2, 3],
#     bar => "bif1"
#   },
#   {
#     foo => [2, 2, 3],
#     bar => "bif2"
#   },
#   ... (8 more)
# ]

my $quoted = join ',', map qq#{foo=>[$_,2,3],bar=>q'bif$_'}#, 1..10;
my $flat   = pack '(N/a)*',
             map pack('N/N N/a', 3, $_, 2, 3, "bif$_"), 1..10;

cmpthese 100000, {
  unquoted => eval "sub {\$a = $quoted}",
  quoted   => sub {$a = eval $quoted},
  eval_one => sub {$a = eval '1'},
  packed   => sub {$a = [map bless([$_], 'foo'), unpack '(N/a)*', $flat]}
};
