#!/bin/bash
catpipe() {
  if (( $1 )); then
    catpipe $(($1 / 2)) | catpipe $(($1 / 2))
  else
    cat
  fi
}

for i in `seq 1200`; do
  cat /usr/share/dict/words
done > testdata

for n in 0 0 1 2 4 8 16 32 64 128 256 512 1024; do
  for i in `seq 10`; do
    echo $n
    time catpipe $n < testdata > /dev/null
  done
done

rm testdata
